# Vector, Matrix Operation & Coding

In [16]:
import numpy as np

In [17]:
#행렬
A = np.array([[3 , 1, 2], [1, -2, 0], [1, 4, 2]])

print(f"A shape : {np.shape(A)}")
print(A)

A shape : (3, 3)
[[ 3  1  2]
 [ 1 -2  0]
 [ 1  4  2]]


In [18]:
#벡터
b = np.array([4, 1, 2])

print(f"b shape : {np.shape(b)}")
print(b)

b shape : (3,)
[4 1 2]


In [19]:
#역행렬
A_inv = np.linalg.inv(A)

print(f"A_inv shape : {np.shape(A_inv)}")
print(A_inv)

A_inv shape : (3, 3)
[[ 2.  -3.  -2. ]
 [ 1.  -2.  -1. ]
 [-3.   5.5  3.5]]


In [20]:
#Ax = b의 x 구하기 -> x = A_inv * b
x = A_inv @ b

print(f"x shape : {np.shape(x)}")
print(x)

x shape : (3,)
[ 1.00000000e+00 -6.66133815e-16  5.00000000e-01]


In [21]:
#결과 검증
bb = A @ x

print(f"bb shape : {np.shape(bb)}")
print(bb)

if np.linalg.norm(b - bb) < 1e-3: #일정 오차보다 작다면 OK
    print("OK")
else:
    print("Not OK")


bb shape : (3,)
[4. 1. 2.]
OK
